#!/bin/bash
#

function publish_to_local {
	return 0
}

function publish_to_npm {
	npm publish --scope public
}

function publish_to_docker {
	local ORGANIZATION="tictactoe"
	local VERSION=$(cat ${PACKAGE_JSON} | jq -r .version)
	local NAME=$(cat ${PACKAGE_JSON} | jq -r .name | tr '/' '\n' | grep -v "^@" | tail -n1)
	echo "name = ${NAME}"
	echo "version = ${VERSION}"
	docker build . && \
		docker build -t ${ORGANIZATION}/${NAME}:${VERSION} . && \
		docker build -t ${ORGANIZATION}/${NAME}:latest . && \
		docker push ${ORGANIZATION}/${NAME}:${VERSION} && \
		docker push ${ORGANIZATION}/${NAME}:latest
}

export TOP_DIR="$(cd "$(dirname "$0")"/../ && pwd)"
export PACKAGE_JSON="${TOP_DIR}/package.json"

TARGET=$1
shift

case "${TARGET}" in
	"")
		publish_to_npm $@
		;;
	npm)
		publish_to_${TARGET} $@
		;;
	docker)
		publish_to_${TARGET} $@
		;;
	local)
		publish_to_${TARGET} $@
		;;
	*)
		echo "unsupported target: ${TARGET}"
		exit 1
esac
